# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 12:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170726_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, db_index=True, default=[], null=True, size=None)),
                ('object_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], null=True, size=None)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
